name: Go
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Install debs
      run: sudo apt update &&
        sudo apt install -y --no-install-recommends
        fontconfig libfreetype6 libjpeg-turbo8
        libx11-6 libxcb1 libxext6 libpng-dev
        libxrender1 xfonts-75dpi xfonts-base &&
        wget -O wkhtmltox.deb https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.trusty_amd64.deb &&
        sudo dpkg -i *.deb &&
        rm -f *.deb

    - name: Install zfvet
      run: go get github.com/riskive/zfvet/cmd/zfvet && GOBIN=/usr/local/bin/ go install github.com/riskive/zfvet/cmd/zfvet

    - name: Run zfvet
      run: zfvet ./...

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v1
      # uses: docker://reviewdog/action-golangci-lint:v1 # pre-build docker image
      with:
        github_token: ${{ secrets.github_token }}

    - name: Build
      run: go build -v .
